### ISSUE TITLE
Version of GPFlow

### ISSUE THREAD

**Issue by laurafroelich** [boschresearch/GP_tutorial#1]
Hi,
Thanks for a nice presentation :)

I cannot run the notebook, I suspect my version  of GPFlow is the issue (I installed GPFlow from git to avoid errors caused by using Tensorflow 2.0). So I wanted to ask which version of GPFlow the notebook was written for?

**Comment by brakitsch** [comment]
Hi Laura,

Thanks for the nice feedback! I used the following configuration:

tensorflow 1.8.0
gpflow       1.2.0

Please let me know if you have any more questions.

Cheers,
Barbara

Mit freundlichen Grüßen / Best regards

Barbara Rakitsch

Differentiating AI - AI-based Physical Modeling (CR/PJ-AI-R1)
Barbara.Rakitsch@de.bosch.com<mailto:Barbara.Rakitsch@de.bosch.com>

**Comment by laurafroelich** [comment]
Hi Barbara,
Thanks for the quick reply. I use Python 3.7 and the lowest available Tensorflow I could find that was compatible was 1.13..0rc1. Using this with GPFlow 1.2.0 works fine, so I can now run the notebook, thanks!
